name: example
description: Beispiel-App für flutter_pickliste_widgets.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter_pickliste_widgets:
    path: ..

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  network_info_plus: ^2.3.2
  package_info_plus: ^2.0.0
  path_provider: ^2.0.11
  go_router: ^5.1.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  # Obwohl das package custom font Dateien bereit stellt, müssen diese - falls benötigt - manuell eingebunden werden.
  # fonts:
  #   - family: RobotoMono
  #     fonts:
  #       - asset: packages/flutter_pickliste_widgets/fonts/RobotoMono-Regular.ttf
  #       - asset: packages/flutter_pickliste_widgets/fonts/RobotoMono-Bold.ttf
