include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_relative_imports: true
    omit_local_variable_types: true
    avoid_dynamic_calls: true
    require_trailing_commas: true
    always_declare_return_types: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
