# .github/workflows/tests.yml

name: tests
on: [workflow_dispatch]

jobs:
  android:
    runs-on: macos-11
    strategy:
      matrix:
        api-level:
          - 31
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm    

      - name: setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.3.4

      - name: install Flutter dependencies
        run: |
             flutter clean
             flutter pub get

      - name: run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: cd example && flutter test integration_test/main_test.dart
